#დაწერეთ პითონის პროგრამა, რომელიც ითვლის მართკუთხედის ფართობს. პროგრამამ უნდა სთხოვოს მომხმარებელს მართკუთხედის სიგანე და სიმაღლე.


#  make the user  enter the width of the rectangle
width = float(input("Please enter the width of the rectangle: "))

# make the user  enter the height of the rectangle
height = float(input("Please enter the height of the rectangle: "))

# Calculate the area of the rectangle
area = width * height
print(area)
